services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root      # Senha para o usuário root
      MYSQL_DATABASE: maquiagem_db     # Cria um banco de dados inicial
      MYSQL_USER: user               # Cria um usuário adicional
      MYSQL_PASSWORD: password       # Senha para o usuário adicional
    ports:
      - "3306:3306"                  # Mapeia a porta do MySQL para o host
    volumes:
      - mysql_data:/var/lib/mysql    # Volume persistente para os dados
    command: --default-authentication-plugin=mysql_native_password  # Usa o método de autenticação compatível com mais clientes

volumes:
  mysql_data:                        # Define o volume persistente