services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root      # Senha para o usuário root
      MYSQL_DATABASE: maquiagem_db     # Cria um banco de dados inicial
      MYSQL_USER: user               # Cria um usuário adicional
      MYSQL_PASSWORD: password       # Senha para o usuário adicional
    ports:
      - "3307:3306"                  # Mapeia a porta do MySQL para o host
    volumes:
      - mysql_data:/var/lib/mysql    # Volume persistente para os dados
    command: --default-authentication-plugin=mysql_native_password  # Usa o método de autenticação compatível com mais clientes

  app:
    build: .
    container_name: loja_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/maquiagem_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  mysql_data:  # Define o volume persistente